version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:f4S4zWSIT5MBCTBWjbnFtli6O7GMze1FiettMDvavjU"
      - run:
          name: Deploy to EC2
          command: |
            ssh ec2-user@ec2-54-216-158-20.eu-west-1.compute.amazonaws.com 'bash -s' < scripts/deploy.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main 
